### ISSUE TITLE
Err :mwbScanner is not defined -  i followed the readme file and copied the homepage and hompe page.ts from example folder.

### ISSUE THREAD

**Issue by bhupathibhargva** [manateeworks/phonegap-manateeworks-v3#12]
Runtime Error
mwbScanner is not defined
Stack
ReferenceError: mwbScanner is not defined
    at HomePage.webpackJsonp.191.HomePage.startScanner (http://localhost:8100/build/main.js:56:9)
    at Object.eval [as handleEvent] (ng:///AppModule/HomePage.ngfactory.js:476:24)
    at handleEvent (http://localhost:8100/build/vendor.js:12273:138)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:13565:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/vendor.js:13153:12)
    at dispatchEvent (http://localhost:8100/build/vendor.js:9173:21)
    at http://localhost:8100/build/vendor.js:9765:20
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/vendor.js:33938:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37)
Ionic Framework: 3.5.3
Ionic App Scripts: 2.0.2
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.11.1
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by bhupathibhargva** [comment]
i m get the following  err with Ionic 2 Demo App.
https://github.com/manateeworks/manateeworks-barcodescanner-ionic2-starter/issues/1
 please help me with this.

**Comment by ghost** [comment]
bhupathibhargva,

We did some changes to the starter app. We updated it to use Ionic 3.6.0. The old code was set to use an Ionic CLI with version ~2.2.1., therefore the structure of the app was incompatible. Additionally, state restore has been deprecated. Instead the plugins are now pulled directly from the configuration file. 

Please follow these new instructions: https://github.com/manateeworks/manateeworks-barcodescanner-ionic-starter. 

Regards,

Team Manatee
